### PR TITLE
5 use of cicd

### LINKED ISSUE #5: Use of CI/CD
Describe the usage of CI/CD in our planned development

### PR DESCRIPTION
**Pull request by KyleJMcMaster**
closes #5

### CODE REVIEW

**Comment by matpetro** [comment]
No mention of testing in the CI/CD plan, is this something we are going to consider, or are we leaving it out for now?

**Comment by KyleJMcMaster** [comment]
> No mention of testing in the CI/CD plan, is this something we are going to consider, or are we leaving it out for now?

Good point - do you have any recs for testing procedure? I expect we will probably just want to focus on server side as FE can be a pain to regression test

**Comment by KyleJMcMaster** [comment]
@matpetro added testing. Ready for review

**Review by matpetro — APPROVED** [review]
Looks good to me, just add an "a" in "We will use suite of tests"

**Pull request merged**
